### ISSUE TITLE
How to post custom raw data with BestHTTP client implement

### ISSUE THREAD

**Issue by dev-shinyu** [sp958857/Retrofit4Unity#1]
Hi.

I'm going to use Post Method to deliver the raw data (byte) to the server.

For reference, the server is a Golang server and tested with Assets: BestHTTP.

Below are the results of actual testing ,

**Unity C# Code Sample**

**BestHTTP Sample # 1**

   HTTPRequest request = new HTTPRequest(new Uri(_builder.ToString()), OnRequestFinished);

 

        if (json!= null)

        {

         

            byte[] data = SnappyCompress(json);

            request.RawData = data;

}

request.MethodType = HTTPMethods.Post;

        request.Tag = transparent;

        request.Send();

 

 

 

**Golang  Server Sample Code**

rawData, _ := ioutil.ReadAll(c.Request().Body)

          log.Println("rawData: ", len(rawData))

 

          data, err := snappy.Decode(nil, rawData)

          json := json.RawMessage(string(data))

          log.Println("json - " + string(json))

 

**BestHttp Request Golang Server Response Valid Result Success!**

2018/11/19 16:24:24 rawData:  79

2018/11/19 16:24:24 json - {"code":"3","key":"null","name":"Frog","desc":"Example Chracter Desc","exp":2}

 

 

Is there any way you can get results like BestHTTP?

Tell me how to do it

 

The intention of the question is to send the raw data to the server and to receive the raw data from the response results.

 

It was possible in best http, but I would like to implement it with retrofit.

Snappy is a high-speed compression algorithm created by Google that significantly reduces packet size and is used in big data.

 

I hope it's resolved quickly

 

**I'll wait for an answer.

Thank you.**

**Comment by sp958857** [comment]
two step to implement this:
1. Use BODY attribute. something like these:
[POST("/users/new")]
IObservable<User> CreateUser(
	[Body] User user);

2.modify your BestHttpImpl.cs, add your compress part to ConfigureRESTfulApi method, like these
    request.RawData =  SnappyCodec.Compress(Encoding.UTF8.GetBytes(methodInfo.bodyString));
 
PS:BestHttpImpl.cs is locate in Retrofit4Unity\Project\Assets\Retrofit4Unity\Integrations\BestHttpImpl.unitypackage
