### ISSUE TITLE
Handle info in response header

### ISSUE THREAD

**Issue by dev-shinyu** [sp958857/Retrofit4Unity#2]
Thank you very much for your thoughtful response.

In fact, it was a question I asked to avoid using BestHttp.
So I do not think I can use BestHtpimpl. In this case, I wonder if you should use the default value HttpClientImpl or if you should set it to UnityWebRequestImpl.

And I have questions about response processing.

1.How to get a value to a specific key value in the response header

In the case of BestHttp, you can get the value in the form of 

**sample:**
 void OnRequestFinished(HTTPRequest req, HTTPResponse res)
 int oriSize = int.Parse(res.GetHeaderValues("ori")[0]);

2. How to get byte array values from response data

In the case of BestHttp

/ / The data that donworld from the servicer. All Transfer and Content encodings decoded if any (eg. chunked, gzip, deflate).
 public byte[] Data { get; internal set; }
.................

**sample:**
 void OnRequestFinished(HTTPRequest req, HTTPResponse res)
String data = SnapyDecompress (res.Data); 

When I used the bestHttp Asset, I was able to bring it this way.

Please let me know how Retrofit can get these values.

Thank you. :)

**Comment by sp958857** [comment]
Retrofit is primarily designed for RESTful API, which means it hypothesize that all the response info is received in response body. even so, there are some tricks to work around.
1.Modify your BestHttpImpl, do everything you want in method RxBuildRequest<T>, so the info in response header can be handled.
2.Same with Question1, RxHttpImplement/HttpImplement is open for modification, in those implementation, all the raw HTTP module class are accessible, the left thing the user need to do is that telling the retrofit how to convert the raw response info to entity you cares. then use Rx to sumbit the result by calling o.OnNext(entity)
